### ISSUE TITLE
Problem in last changes to httpclient

### ISSUE THREAD

**Issue by angoyd** [ON-IT/Visma.Net#123]
I have noised that we got problems with the latest changes that was made to support concurrent fetching of pages and paging, it works fine in local dev environment (win 10) but we get timeouts and long times for small answers (ie get a customer can time out) when running in our Azure Function environment, haven´t found exactly whats the problem jet but thoght you might have som ideas @omelhus?

**Comment by omelhus** [comment]
Customer.Get(number) times out? This is not affected by the changes. Can you provide some examples?

**Comment by angoyd** [comment]
I´m getting the following exception and stacktrace, but it only happens in azure environment

A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ONIT.VismaNetApi.Lib.VismaNetHttpClient.<Post>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ONIT.VismaNetApi.Lib.VismaNetApiHelper.<Create>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ONIT.VismaNetApi.Lib.Data.BaseCrudDataClass`1.<Add>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CallSite.Target(Closure , CallSite , Object )
   at TraventusCommonFunctions.ExtensionMethods.<InvokeAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at TraventusCommonFunctions.OrchestrationFunctions.ImportRowsFromSQLFunction.<Run>d__0.MoveNext()

**Comment by angoyd** [comment]
I haven´t been able to reproduce this error so I close the issue for now.
